[
  {
    "Advisory": {
      "Classification": "GENERAL",
      "Severity": "Critical",
      "CVSS": {
        "version": "3.1",
        "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "base_metrics": {
          "base_score": 9.8,
          "exploitability_score": 3.9,
          "impact_score": 5.9,
          "base_severity": "Critical"
        },
        "status": "N/A"
      },
      "FixedIn": [
        {
          "name": "scratch-vm",
          "identifier": "0.2.0-prerelease.20200714185213",
          "ecosystem": "npm",
          "namespace": "github:npm",
          "range": "<= 0.2.0-prerelease.20200709173451"
        }
      ],
      "Summary": "Remote Code Execution in scratch-vm",
      "url": "https://github.com/advisories/GHSA-vc9j-fhvv-8vrf",
      "CVE": [
        "CVE-2020-14000"
      ],
      "Metadata": {
        "CVE": [
          "CVE-2020-14000"
        ]
      },
      "ghsaId": "GHSA-vc9j-fhvv-8vrf",
      "published": "2020-07-27T19:55:52Z",
      "updated": "2023-01-09T05:03:39Z",
      "withdrawn": null,
      "namespace": "github:npm"
    },
    "Vulnerability": {}
  },
  {
    "Advisory": {
      "CVE": [
        "CVE-2018-8768"
      ],
      "FixedIn": [
        {
          "ecosystem": "python",
          "identifier": "5.4.1",
          "name": "notebook",
          "namespace": "github:python",
          "range": "< 5.4.1"
        }
      ],
      "Metadata": {
        "CVE": [
          "CVE-2018-8768"
        ]
      },
      "Severity": "Low",
      "Summary": "Low severity vulnerability that affects notebook",
      "ghsaId": "GHSA-6cwv-x26c-w2q4",
      "namespace": "github:python",
      "url": "https://github.com/advisories/GHSA-6cwv-x26c-w2q4",
      "withdrawn": "2022-01-31T14:32:09Z"
    },
    "Vulnerability": {}
  },
  {
    "Advisory": {
      "CVE": [
        "CVE-2017-5524"
      ],
      "FixedIn": [
        {
          "ecosystem": "python",
          "identifier": "4.3.12",
          "name": "Plone",
          "namespace": "github:python",
          "range": ">= 4.0 < 4.3.12"
        },
        {
          "ecosystem": "python",
          "identifier": "5.1b1",
          "name": "Plone",
          "namespace": "github:python",
          "range": ">= 5.1a1 < 5.1b1"
        },
        {
          "ecosystem": "python",
          "identifier": "5.0.7",
          "name": "Plone-debug",
          "namespace": "github:python",
          "range": ">= 5.0rc1 < 5.0.7"
        }
      ],
      "Metadata": {
        "CVE": [
          "CVE-2017-5524"
        ]
      },
      "Severity": "Medium",
      "Summary": "Moderate severity vulnerability that affects Plone",
      "ghsaId": "GHSA-p5wr-vp8g-q5p4",
      "namespace": "github:python",
      "url": "https://github.com/advisories/GHSA-p5wr-vp8g-q5p4",
      "withdrawn": null
    },
    "Vulnerability": {}
  },
  {
    "Advisory": {
      "CVE": [
        "CVE-2017-5524"
      ],
      "FixedIn": [
        {
          "ecosystem": "python",
          "identifier": "4.3.12",
          "name": "Plone",
          "namespace": "github:python",
          "range": ">= 4.0 < 4.3.12"
        },
        {
          "ecosystem": "python",
          "identifier": "5.1b1",
          "name": "Plone",
          "namespace": "github:python",
          "range": ">= 5.1a1 < 5.1b1"
        },
        {
          "ecosystem": "python",
          "identifier": "5.0.7",
          "name": "Plone-debug",
          "namespace": "github:python",
          "range": ">= 5.0rc1 < 5.0.7"
        }
      ],
      "Metadata": {
        "CVE": [
          "CVE-2017-5524"
        ]
      },
      "Severity": "Medium",
      "Summary": "Moderate severity vulnerability that affects Plone",
      "ghsaId": "",
      "namespace": "github:python",
      "url": "https://github.com/advisories/GHSA-p5wr-vp8g-q5p4",
      "withdrawn": null
    },
    "Vulnerability": {}
  },
  {
    "Advisory": {
      "CVE": [
        "CVE-2017-5524"
      ],
      "FixedIn": [
        {
          "ecosystem": "python",
          "identifier": "4.3.12",
          "name": "Plone",
          "namespace": "github:python",
          "range": ">= 4.0 < 4.3.12"
        },
        {
          "ecosystem": "python",
          "identifier": "5.1b1",
          "name": "Plone",
          "namespace": "github:python",
          "range": ">= 5.1a1 < 5.1b1"
        },
        {
          "ecosystem": "python",
          "identifier": "5.0.7",
          "name": "Plone-debug",
          "namespace": "github:python",
          "range": ">= 5.0rc1 < 5.0.7"
        }
      ],
      "Metadata": {
        "CVE": [
          "CVE-2017-5524"
        ]
      },
      "Severity": "Medium",
      "Summary": "Moderate severity vulnerability that affects Plone",
      "namespace": "github:python",
      "url": "https://github.com/advisories/GHSA-p5wr-vp8g-q5p4",
      "withdrawn": null
    },
    "Vulnerability": {}
  }
]

